pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // This pulls your code from Git
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // This runs your Makefile just like you do in the terminal
                sh 'make clean'
                sh 'make'
            }
        }

        stage('Test') {
            steps {
                // Execute your test binary generated by the Makefile
                sh './client'
            }
        }

        post {
        // This runs regardless of whether the build succeeded or failed
        // But usually, you only want to save artifacts on success
        success {
            archiveArtifacts artifacts: 'clienttest', fingerprint: true
        }
    }
    }
}